[project]
name = "fortniteskinchecker"
version = "0.1.0"
description = "A Discord bot that displays Fortnite account skins and profile information using the official Epic Games API."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]
